### ISSUE TITLE
Фикс

### ISSUE THREAD

**Issue by X88Y** [superdima05/mesh#1]
Буду рад указанию авторства(Duxk from 228iQ) нужно делать запрос не 'spec' а 'homework'
VK - vk.com/6x88y9

**Comment by superdima05** [comment]
Здравствуйте! Сделал запрос по адресу https://uchebnik.mos.ru/exam/rest/secure/api/binding/"+ID теста+"/homework со всеми cookie, но ответ пришёл 404 Not Found. Можно точный URL?

`{"timestamp":"2020-12-21T18:18:38.717+0000","status":404,"error":"Not Found","message":"Not Found","path":"/rest/secure/api/binding/212891/homework"}`

**Comment by X88Y** [comment]
Можешь отписать в вк

**Comment by superdima05** [comment]
ВК нету, могу в Telegram

**Comment by X88Y** [comment]
YoungDuxk
