### ISSUE TITLE
Метод для получения названия теста

### ISSUE THREAD

**Issue by NEVERMORE102** [superdima05/mesh#13]
Сделайте метод, чтобы ты вставлял ссылку на тест и получал его название.

**Comment by superdima05** [comment]
Здравствуйте! К сожалению, сейчас у нас нету времени на добавление этой опции.

**Comment by NEVERMORE102** [comment]
А что в планах добавить, если есть? Моё предложение, это добавить премиум версию.

**Comment by mishailovic** [comment]
> А что в планах добавить, если есть? Моё предложение, это добавить премиум версию.

Она не будет никем использоваться, тем более это open source проект. Вам нужно монетизировать библиотеку, ради бога, но сюда это нести не нужно

**Comment by mishailovic** [comment]
Обыскал все методы, всё что нашёл это `https://uchebnik.mos.ru/webtests/exam/rest/secure/api/spec/bind/{номерварианта}`
Но работает только для ученических учеток, и только если тест начат, иначе выдаст ошибку: `тестового материала к внешней сущности не найдена в базе данных`
Может @superdima05 и @kinda-cookie-monster что-то придумают, т. к. у меня идей больше нет

**Comment by mishailovic** [comment]
#22 Добавил

**Comment by kinda-cookie-monster** [comment]
Принято! :)
