### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by N0N1m3** [superdima05/mesh#2]
Не работает функцию auth, от слова вообще.

**Comment by superdima05** [comment]
Какую ошибку выдает Python?

**Comment by N0N1m3** [comment]
Ну  я проверил и функцию, она ничего не отдает. И возникает такая ошибка: 
cookies = {"auth_token": authd['authentication_token'], "profile_id": str(authd['profiles'][0]['user_id']), "profile_id": str(authd['id']), "udacl": "resh"}
TypeError: 'NoneType' object is not subscriptable

**Comment by superdima05** [comment]
Попробуй создать файл last со следующим содержанием: `{"id":1000000000,"profiles":[{"id":1000000000,"type":"demo","roles":[],"user_id":1000000000,"agree_pers_data":false,"agreement_accepted":false,"subject_ids":[]}],"phone_number":"","authentication_token":"","password_change_required":false,"activity":[]} `

**Comment by N0N1m3** [comment]
Какое расширение для файла last?

**Comment by superdima05** [comment]
Никакое

**Comment by N0N1m3** [comment]
Благодарю, все заработало)
