### ISSUE TITLE
Краши при решении некоторых тестов.

### ISSUE THREAD

**Issue by mishailovic** [superdima05/mesh#21]
1) `https://uchebnik.mos.ru/exam/test/test_by_binding/15620170/homework/151260635/`

Ошибка:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hotaru/mesh/mesh.py", line 155, in get_answers
    statement += generate_string(string_chunk)
  File "/home/hotaru/mesh/mesh.py", line 119, in generate_string
    return text.format(*options)
KeyError: ' 5; —3; z '`

2) `https://uchebnik.mos.ru/exam/test/test_by_binding/15472188/homework/150366233`

Ошибка:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hotaru/mesh/mesh.py", line 155, in get_answers
    statement += generate_string(string_chunk)
TypeError: can only concatenate str (not "NoneType") to str`

**Comment by kinda-cookie-monster** [comment]
Сделано!

**Comment by mishailovic** [comment]
> Сделано!

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hotaru/mesh/mesh.py", line 306, in get_answers
    answer_dict [index] = cell_names [index] | answer_cells [index]
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by mishailovic** [comment]
Как насчёт ловить ошибки в каждом типе задания, и возвращать ошибку в самом задании, вместо фатального краша всей библиотеки?

**Comment by kinda-cookie-monster** [comment]
`Как насчёт ловить ошибки в каждом типе задания, и возвращать ошибку в самом задании, вместо фатального краша всей библиотеки?`
Да, можно! Да вот код в последнее время превращается в кучу спагетти. Скоро планирую все переписать, тогда, возможно, и добавлю этот фунционал.

И еще такой вопрос. У вас какая версия Python стоит?

**Comment by mishailovic** [comment]
Да, я бы вынес каждый вид задания в отдельный файл, и использовал их как модули. Насчёт питона - уже понял что это функции из новой версии, а из репозиториев Ubuntu последний python3 версии 3.8
