### ISSUE TITLE
Ошибка при получении ответов

### ISSUE THREAD

**Issue by mishailovic** [superdima05/mesh#3]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\mesh\mesh.py", line 80, in get_answers
    r = json.loads(r.text)['training_tasks']
KeyError: 'training_tasks'
```

**Comment by superdima05** [comment]
Если указать c_type="homework", то ошибка останется?

**Comment by mishailovic** [comment]
Да, ошибка остаётся

**Comment by superdima05** [comment]
К сожалению, ошибка видимо на стороне МЭШ. У нас бот тоже сейчас не работает и выкладывает похожую ошибку

**Comment by mishailovic** [comment]
Надеюсь на скорое исправление) а то нас закидали тестами цдз

**Comment by mishailovic** [comment]
Нашёл фикс, но пока только для тестов типа 'spec'. Выполняем пост запрос на https://uchebnik.mos.ru/exam/rest/secure/testplayer/group с json телом вида:
```
{"test_type":"training_test","generation_context_type":"spec","generation_by_id":"271948"}
```
И куками соответственно. В ответ получаем ответы обычного вида: https://pastebin.com/QqJfAPqy

**Comment by mishailovic** [comment]
Скорее всего нужно копать в сторону spec тестов, а конкретно получение их айди имея айди теста типа homework

**Comment by mishailovic** [comment]
Кстати, на эндпоинте https://uchebnik.mos.ru/exam/rest/secure/api/training/generate теперь ответов нет, везде стоит null

**Comment by superdima05** [comment]
Насчёт endpoint generate мы знаем, а вот ваш метод на одно сообщение выше нас заинтересовал. Постараемся реализовать.

**Comment by superdima05** [comment]
Вроде каждый тест является spec. Наверное мы сможем реализовать для всех тестов

**Comment by superdima05** [comment]
> Нашёл фикс, но пока только для тестов типа 'spec'. Выполняем пост запрос на https://uchebnik.mos.ru/exam/rest/secure/testplayer/group с json телом вида:
> 
> ```
> 
> {"test_type":"training_test","generation_context_type":"spec","generation_by_id":"271948"}
> 
> ```
> 
> И куками соответственно. В ответ получаем ответы обычного вида: https://pastebin.com/QqJfAPqy
> 
> 

C demo аккаунтом не проверяли?

**Comment by superdima05** [comment]
> > Нашёл фикс, но пока только для тестов типа 'spec'. Выполняем пост запрос на https://uchebnik.mos.ru/exam/rest/secure/testplayer/group с json телом вида:
> > 
> > ```
> > 
> > {"test_type":"training_test","generation_context_type":"spec","generation_by_id":"271948"}
> > 
> > ```
> > 
> > И куками соответственно. В ответ получаем ответы обычного вида: https://pastebin.com/QqJfAPqy
> > 
> > 
> 
> C demo аккаунтом не проверяли?

С demo аккаунтом работает. Это хорошая новость, ведь аккаунты стали часто уходить в бан

**Comment by X88Y** [comment]
Можно вопрос, а что за демо аккаунт?

**Comment by superdima05** [comment]
Аккаунт под которым МЭШ заходит по умолчанию. Он ничего не дает сделать, используя front end, но, используя backend, можно получать тесты (сейчас пофиксили, но новый метод еще нет)

**Comment by olegoleg1111121** [comment]
Разработчики МЭШ вкурсе данной уязвимости и работают над её устранением.

**Comment by mishailovic** [comment]
> Разработчики МЭШ вкурсе данной уязвимости и работают над её устранением.

Чем подкреплена данная информация?

**Comment by superdima05** [comment]
Я думаю МЭШ знает об этом. Наверное, они даже знают где фиксить, благодаря этому репозиторию

**Comment by mishailovic** [comment]
Одно могу сказать точно, чем быстрее они закроют все дыры, тем будет лучше. Админы ботов в вк зарабатывают огромные деньги на школьниках просто воруя у друг друга однотипный код подкрепленный одной уязвимостью. Типичный бот для решения цдз просит 10 рублей за решение домашки, думаю в масштабе Москвы выходит нехилая сумма.

**Comment by superdima05** [comment]
Согласен

**Comment by olegoleg1111121** [comment]
> Одно могу сказать точно, чем быстрее они закроют все дыры, тем будет лучше. Админы ботов в вк зарабатывают огромные деньги на школьниках просто воруя у друг друга однотипный код подкрепленный одной уязвимостью. Типичный бот для решения цдз просит 10 рублей за решение домашки, думаю в масштабе Москвы выходит нехилая сумма.

А что плохого в таком заработке?)

**Comment by superdima05** [comment]
Ученики школ ничего не хотят делать и просто всё списывают

**Comment by olegoleg1111121** [comment]
Да, по основной части.

**Comment by 0x04D8E470** [comment]
> Нашёл фикс, но пока только для тестов типа 'spec'. Выполняем пост запрос на https://uchebnik.mos.ru/exam/rest/secure/testplayer/group с json телом вида:
> 
> ```
> {"test_type":"training_test","generation_context_type":"spec","generation_by_id":"271948"}
> ```
> 
> И куками соответственно. В ответ получаем ответы обычного вида: https://pastebin.com/QqJfAPqy

Если это все еще требуется, но для получения ответов на обычный тест (test_by_binding), требуется изменить немного тело json'a

```
{"test_type":"training_test","generation_context_type":"homework","generation_by_id":"ID test_by_binding"}
```

**Comment by mishailovic** [comment]
Заработали тесты типа 'homework' нужно просто заменить некоторые значения в json коде
{"test_type":"training_test","generation_context_type":"homework","generation_by_id":"12345678"}

**Comment by superdima05** [comment]
Обновил библиотеку [последний commit](https://github.com/superdima05/mesh/commit/2ff65c276e992d6718c05928258ff9eb07715a75)

**Comment by mishailovic** [comment]
> Эта уязвимость всё ещё существует. Плохо работают что-то

Просто платформа тестов заказывалась как готовый продукт, никто чинить его не будет

**Comment by Grigoriy457** [comment]
![image](https://user-images.githubusercontent.com/77736651/164294162-2b553636-c907-4219-88ad-4e46d3036b1b.png)
Кто может подсказать что это за виды заданий (желательно со скринами)?

**Comment by glebat28-dev** [comment]
Вышел новый тип теста "challenge"

**Comment by glebat28-dev** [comment]
@superdima05 @mishailovic Кто-то ещё жив?

**Comment by mishailovic** [comment]
> [@superdima05](https://github.com/superdima05) [@mishailovic](https://github.com/mishailovic) Кто-то ещё жив?

Я уже три года как окончил школу :)
Очень сомневаюсь, что чем-то могу помочь. 

В последний раз когда тыкал несколько лет назад личные кабинеты, оказалось, что на ученических аккаунтах полностью закрыли все уязвимости, соответственно единственным способом получения ответов является их парсинг с учительского акка, чем собственно сейчас и занимаются оставшиеся в телеграмме/вк боты.

**Comment by dmitzsaz** [comment]
> [@superdima05](https://github.com/superdima05) [@mishailovic](https://github.com/mishailovic) Кто-то ещё жив?

Я жив) но я уже ВУЗ успел закончить ;) Едва ли буду завозить апдейты к либе — я вообще не знаю, что в МЭШе сейчас происходит.

**Comment by mishailovic** [comment]
> > [@superdima05](https://github.com/superdima05) я вообще не знаю, что в МЭШе сейчас происходит.

Я слышал, что теперь у МЭШа есть полноценная команда, а не аутсорс как раньше, собственно почему они и пофиксили все уязвимости

**Comment by mishailovic** [comment]
@superdima05 если не будет обнов напиши об этом в ридми и заархивируй репо, так будет лучше
