### ISSUE TITLE
Вебсайт

### ISSUE THREAD

**Issue by mishailovic** [superdima05/mesh#8]
Приветствую! Сделал вебсайт с помощью вашей библиотеки, буду очень рад если добавите его в README.md
https://mash.hotaru.ga/

**Comment by superdima05** [comment]
Привет! Проверил вчера сайт, но он не смог решить не один тест. Обнови сайт, используя последнюю версию библиотеки.

**Comment by mishailovic** [comment]
Привет. Проверил все ещё несколько раз, работает как положено. Выдаёт то что неверная ссылка, или просто долгая загрузка? Если второе то все нормально, почему то с моего хостинг провайдера на мэш запросы поступают очень медленно. Так же кнопка "решить" является неактивной во время записи в окошко, так что на нее нужно нажать два раза.

![Screenshot_2021-04-29-00-21-13-865_com android chrome](https://user-images.githubusercontent.com/41520056/116474189-db181180-a880-11eb-8d80-bf667b992a3e.jpg)

**Comment by superdima05** [comment]
Сайт работает! Скоро добавим в README.md
