### ISSUE TITLE
Решение вопросов типа "answer/gap/match/text"

### ISSUE THREAD

**Issue by mishailovic** [superdima05/mesh#9]

**Comment by kinda-cookie-monster** [comment]
К сожалению, нам ни разу не попадался данный тип заданий в наших тестах. Поэтому во время переработки, его не добавили. Был бы благодарен, если бы вы скинули ссылку на тест, в котором вам попался данный тип. Это помогло бы нам добавить необходимый функционал.

**Comment by mishailovic** [comment]
Привет! Вот ссылка на тест: https://uchebnik.mos.ru/exam/test/test_by_binding/13958878/homework/140283311?generation_context_type=homework

**Comment by kinda-cookie-monster** [comment]
Хорошие новости! Ваша проблема была исправлена и данный тип заданий теперь работает. Но пока проблему закрывать не будем, пока вы не отпишетесь о работе бота после фикса. :)

**Comment by mishailovic** [comment]
спасибо огромное, теперь всё работает)
